<?php
/**
 * Plugin Name: Ecwid AJAX Product Search
 * Description: Adds a live AJAX search bar for Ecwid store products with search button, full-width results & popular brands.
 * Version: 1.2
 * Author: Your Name
 */

if (!defined('ABSPATH')) exit;

// Enqueue scripts & styles
add_action('wp_enqueue_scripts', function () {
    wp_enqueue_script('ecwid-search-js', plugin_dir_url(__FILE__) . 'ecwid-search.js', ['jquery'], null, true);
    wp_localize_script('ecwid-search-js', 'ecwidSearch', [
        'ajaxUrl' => admin_url('admin-ajax.php'),
        'minChars'=> 3
    ]);
    wp_enqueue_style('ecwid-search-css', plugin_dir_url(__FILE__) . 'ecwid-search.css');
});

// Shortcode for search bar
add_shortcode('ecwid_search', function () {
    return '<div class="ecwid-search-wrapper">
        <input type="text" id="ecwid-search-input" placeholder="Type Atleast 3 letters">
        <button id="ecwid-search-btn">SEARCH</button>
        <div id="ecwid-search-results">
            <div class="ecwid-popular">
                <span>Popular Searches:</span> 
                <a href="#" class="ecwid-pop-item">Brand A</a>, 
                <a href="#" class="ecwid-pop-item">Brand B</a>
            </div>
        </div>
    </div>';
});

// AJAX handler
add_action('wp_ajax_ecwid_search', 'ecwid_ajax_search');
add_action('wp_ajax_nopriv_ecwid_search', 'ecwid_ajax_search');

function ecwid_ajax_search() {
    $q = sanitize_text_field($_GET['q'] ?? '');
    if (strlen($q) < 3) {
        wp_send_json_error('Too short');
    }

    $store_id = '106511509';
    $token    = 'secret_XVdFK6bxhCUEgbH9WYzDyziSWGFhThFK';

    // Get a large batch of products to simulate autocomplete
    $api_url  = "https://app.ecwid.com/api/v3/$store_id/products?limit=100";

    $response = wp_remote_get($api_url, [
        'headers' => ['Authorization' => "Bearer $token"]
    ]);

    if (is_wp_error($response)) {
        wp_send_json_error($response->get_error_message());
    }

    $data = json_decode(wp_remote_retrieve_body($response), true);
    $results = [];

    foreach ($data['items'] ?? [] as $item) {
        if (stripos($item['name'], $q) !== false) {
            $results[] = [
                'id'    => $item['id'],
                'name'  => $item['name'],
                'image' => $item['imageUrl'],
                'price' => $item['defaultDisplayedPriceFormatted'],
                'url'   => "/product/{$item['autogeneratedSlug']}-{$item['id']}/"
            ];
        }
    }

    wp_send_json_success($results);
}
