<?php
/**
 * Plugin Name: Ecwid AJAX Product Search
 * Description: Adds a live AJAX search bar for Ecwid store products.
 * Version: 1.0
 * Author: Your Name
 */

if (!defined('ABSPATH')) exit;

// Enqueue JS & CSS
add_action('wp_enqueue_scripts', function () {
    wp_enqueue_script('ecwid-search-js', plugin_dir_url(__FILE__) . 'ecwid-search.js', ['jquery'], null, true);
    wp_localize_script('ecwid-search-js', 'ecwidSearch', [
        'ajaxUrl' => admin_url('admin-ajax.php'),
        'minChars' => 3
    ]);
    wp_enqueue_style('ecwid-search-css', plugin_dir_url(__FILE__) . 'ecwid-search.css');
});

// Shortcode
add_shortcode('ecwid_search', function () {
    return '<div class="ecwid-search-container">
        <input type="text" id="ecwid-search-input" placeholder="Search products...">
        <div id="ecwid-search-results"></div>
    </div>';
});

// AJAX handler
add_action('wp_ajax_ecwid_search', 'ecwid_ajax_search');
add_action('wp_ajax_nopriv_ecwid_search', 'ecwid_ajax_search');

function ecwid_ajax_search() {
    $query = sanitize_text_field($_GET['q'] ?? '');
    if (strlen($query) < 3) wp_send_json_error('Too short');

    $store_id = '106511509';
    $api_token = 'secret_XVdFK6bxhCUEgbH9WYzDyziSWGFhThFK';
    $url = "https://app.ecwid.com/api/v3/$store_id/products?keyword=" . urlencode($query) . "&limit=6";

    $response = wp_remote_get($url, [
        'headers' => ['Authorization' => "Bearer $api_token"]
    ]);

    if (is_wp_error($response)) {
        wp_send_json_error($response->get_error_message());
    }

    $data = json_decode(wp_remote_retrieve_body($response), true);
    $results = [];

    foreach ($data['items'] ?? [] as $item) {
        $results[] = [
            'id' => $item['id'],
            'name' => $item['name'],
            'image' => $item['imageUrl'],
            'price' => $item['defaultDisplayedPriceFormatted'],
            'url' => "/product/{$item['autogeneratedSlug']}-{$item['id']}/"
        ];
    }

    wp_send_json_success($results);
}
